#! /bin/bash

DOCKER=${DOCKER:-docker}
IMG_PREFIX=christopherferreira/vhive

docker-build() {
	name=$1; shift

	path=image/$name
	tag=${IMG_PREFIX}-$(echo $name | tr '/' '-')

	$DOCKER build ${path} -t ${tag} \
		--build-arg PYTHON_BASE_IMG=${IMG_PREFIX}-base-python
}

docker-build base/python
docker-build chameleon
docker-build float_operation
docker-build image_processing
docker-build linpack
docker-build mapreduce/driver
docker-build mapreduce/mapper
docker-build mapreduce/reducer
docker-build matmul
#docker-build model_training
docker-build pyaes
#docker-build video_processing
