#! /bin/bash

DOCKER=${DOCKER:-docker}
IMG_PREFIX=christopherferreira/vhive
MINIO_IP=172.17.0.3

workload=$1; shift

$DOCKER run -ti \
	-p 50051:50051 \
	-e MINIO_URL="http://${MINIO_IP}:9000" \
	-e MINIO_ACCESSKEYID="minioadmin" \
	-e MINIO_SECRETACCESSKEY="minioadmin" \
	-e VHIVE_GATEWAY_URL="192.168.1.240.xip.io" \
	-e VHIVE_NAMESPACE_NAME="default" \
	"${IMG_PREFIX}-${workload}" \
	"$@"
