#! /bin/bash

DOCKER=${DOCKER:-docker}
IMG_PREFIX=christopherferreira/vhive
MINIO_IP=${MINIO_IP:-172.17.0.2}

workload=$1; shift

$DOCKER run -ti \
	-p 50051:50051 \
	-e MINIO_URL="http://${MINIO_IP}:9000" \
	-e MINIO_ACCESSKEYID="minioadmin" \
	-e MINIO_SECRETACCESSKEY="minioadmin" \
	"${IMG_PREFIX}-${workload}" \
	"$@"
